# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2020-02-23 16:08
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import simple_history.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('decisions', '0016_auto_20190309_2237'),
    ]

    operations = [
        migrations.CreateModel(
            name='HistoricalModule3',
            fields=[
                ('id', models.IntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('answers', models.TextField(default='')),
                ('at', models.TextField(default='')),
                ('at2', models.TextField(default='')),
                ('at2_most', models.TextField(default='')),
                ('at3', models.TextField(default='')),
                ('at3_most', models.TextField(default='')),
                ('cc', models.TextField(default='')),
                ('dd_as_question', models.TextField(default='')),
                ('feeling_end', models.TextField(default='')),
                ('feeling_start', models.TextField(default='')),
                ('pro_con_least', models.TextField(default='')),
                ('pro_con_most', models.TextField(default='')),
                ('problem_to_solve', models.TextField(default='')),
                ('vs', models.TextField(default='')),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_date', models.DateTimeField()),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('course', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='decisions.Course')),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': 'history_date',
                'verbose_name': 'historical Module 4 Data - Backpocket AREA',
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name='Module3',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('completed_on', models.DateField(null=True)),
                ('step', models.CharField(default='', max_length=20)),
                ('answers', models.TextField(default='')),
                ('at', models.TextField(default='')),
                ('at2', models.TextField(default='')),
                ('at2_most', models.TextField(default='')),
                ('at3', models.TextField(default='')),
                ('at3_most', models.TextField(default='')),
                ('cc', models.TextField(default='')),
                ('dd_as_question', models.TextField(default='')),
                ('feeling_end', models.TextField(default='')),
                ('feeling_start', models.TextField(default='')),
                ('pro_con_least', models.TextField(default='')),
                ('pro_con_most', models.TextField(default='')),
                ('problem_to_solve', models.TextField(default='')),
                ('vs', models.TextField(default='')),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='decisions.Course')),
            ],
            options={
                'verbose_name': 'Module 4 Data - Backpocket AREA',
                'verbose_name_plural': 'Module 4 Data - Backpocket AREA',
            },
        ),
    ]
