# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2020-02-25 06:32
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('module3', '0002_auto_20200223_1630'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalmodule3',
            name='success_terms',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='module3',
            name='success_terms',
            field=models.TextField(default=''),
        ),
    ]
