# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2020-03-02 23:35
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('module3', '0004_auto_20200225_2128'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalmodule3',
            name='biases',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='module3',
            name='biases',
            field=models.TextField(default=''),
        ),
    ]
