# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2020-03-10 03:49
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('module3', '0007_auto_20200309_0439'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalmodule3',
            name='at5',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='historicalmodule3',
            name='at5_least',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='historicalmodule3',
            name='at5_most',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='module3',
            name='at5',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='module3',
            name='at5_least',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='module3',
            name='at5_most',
            field=models.TextField(default=''),
        ),
    ]
