# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2020-03-12 03:26
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('module3', '0008_auto_20200310_0349'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalmodule3',
            name='good_prospects',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='historicalmodule3',
            name='great_questions',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='module3',
            name='good_prospects',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='module3',
            name='great_questions',
            field=models.TextField(default=''),
        ),
    ]
