# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2020-03-12 22:03
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('module3', '0009_auto_20200312_0326'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalmodule3',
            name='gq_1',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='historicalmodule3',
            name='gq_2',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='historicalmodule3',
            name='gq_3',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='module3',
            name='gq_1',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='module3',
            name='gq_2',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='module3',
            name='gq_3',
            field=models.TextField(default=''),
        ),
    ]
