# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2020-03-13 02:34
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('module3', '0011_auto_20200313_0000'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalmodule3',
            name='cah1',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='historicalmodule3',
            name='cah2',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='historicalmodule3',
            name='cah3',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='historicalmodule3',
            name='cah4',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='historicalmodule3',
            name='cah5',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='module3',
            name='cah1',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='module3',
            name='cah2',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='module3',
            name='cah3',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='module3',
            name='cah4',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='module3',
            name='cah5',
            field=models.TextField(default=''),
        ),
    ]
