# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2020-03-13 02:45
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('module3', '0012_auto_20200313_0234'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalmodule3',
            name='safeguards',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='module3',
            name='safeguards',
            field=models.TextField(default=''),
        ),
    ]
