# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2020-03-13 03:03
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('module3', '0013_auto_20200313_0245'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalmodule3',
            name='conviction_confidence',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='historicalmodule3',
            name='conviction_decision',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='historicalmodule3',
            name='conviction_rate',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='historicalmodule3',
            name='conviction_why',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='module3',
            name='conviction_confidence',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='module3',
            name='conviction_decision',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='module3',
            name='conviction_rate',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='module3',
            name='conviction_why',
            field=models.TextField(default=''),
        ),
    ]
