# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2020-04-06 03:26
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('module3', '0014_auto_20200313_0303'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalmodule3',
            name='my_options',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='module3',
            name='my_options',
            field=models.TextField(default=''),
        ),
    ]
