# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2020-02-17 05:39
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backpocket', '0002_auto_20200217_0524'),
    ]

    operations = [
        migrations.AddField(
            model_name='backpocket',
            name='cc',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='backpocket',
            name='vs',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='historicalbackpocket',
            name='cc',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='historicalbackpocket',
            name='vs',
            field=models.TextField(default=''),
        ),
    ]
