# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2020-02-17 06:17
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backpocket', '0003_auto_20200217_0539'),
    ]

    operations = [
        migrations.AddField(
            model_name='backpocket',
            name='at',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='historicalbackpocket',
            name='at',
            field=models.TextField(default=''),
        ),
    ]
