# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2020-02-17 06:31
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backpocket', '0004_auto_20200217_0617'),
    ]

    operations = [
        migrations.AddField(
            model_name='backpocket',
            name='at2',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='backpocket',
            name='at3',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='historicalbackpocket',
            name='at2',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='historicalbackpocket',
            name='at3',
            field=models.TextField(default=''),
        ),
    ]
