# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2020-02-17 15:37
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backpocket', '0006_auto_20200217_0703'),
    ]

    operations = [
        migrations.AddField(
            model_name='backpocket',
            name='pro_con_least',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='backpocket',
            name='pro_con_most',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='historicalbackpocket',
            name='pro_con_least',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='historicalbackpocket',
            name='pro_con_most',
            field=models.TextField(default=''),
        ),
    ]
