# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2020-02-19 05:42
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backpocket', '0007_auto_20200217_1537'),
    ]

    operations = [
        migrations.AddField(
            model_name='backpocket',
            name='feeling_end',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='backpocket',
            name='feeling_start',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='historicalbackpocket',
            name='feeling_end',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='historicalbackpocket',
            name='feeling_start',
            field=models.TextField(default=''),
        ),
    ]
